//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKLibrary.DosyaServisi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SenfoniFiles", Namespace="http://server/LKERP/Service/")]
    [System.SerializableAttribute()]
    public partial class SenfoniFiles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileByteArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileByteArray {
            get {
                return this.FileByteArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FileByteArrayField, value) != true)) {
                    this.FileByteArrayField = value;
                    this.RaisePropertyChanged("FileByteArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server/LKERP/Service/", ConfigurationName="DosyaServisi.IFileOperationServices")]
    public interface IFileOperationServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/LKERP/Service/IFileOperationServices/GetFile", ReplyAction="http://server/LKERP/Service/IFileOperationServices/GetFileResponse")]
        LKLibrary.DosyaServisi.SenfoniFiles GetFile(string fullPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/LKERP/Service/IFileOperationServices/SaveFile", ReplyAction="http://server/LKERP/Service/IFileOperationServices/SaveFileResponse")]
        string SaveFile(LKLibrary.DosyaServisi.SenfoniFiles file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/LKERP/Service/IFileOperationServices/CreateDirectory", ReplyAction="http://server/LKERP/Service/IFileOperationServices/CreateDirectoryResponse")]
        bool CreateDirectory(string filePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileOperationServicesChannel : LKLibrary.DosyaServisi.IFileOperationServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileOperationServicesClient : System.ServiceModel.ClientBase<LKLibrary.DosyaServisi.IFileOperationServices>, LKLibrary.DosyaServisi.IFileOperationServices {
        
        public FileOperationServicesClient() {
        }
        
        public FileOperationServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileOperationServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileOperationServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileOperationServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LKLibrary.DosyaServisi.SenfoniFiles GetFile(string fullPath) {
            return base.Channel.GetFile(fullPath);
        }
        
        public string SaveFile(LKLibrary.DosyaServisi.SenfoniFiles file) {
            return base.Channel.SaveFile(file);
        }
        
        public bool CreateDirectory(string filePath) {
            return base.Channel.CreateDirectory(filePath);
        }
    }
}
