//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKUI.EntegrasyonServisi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntegrasyonServisi.IEntegrasyon")]
    public interface IEntegrasyon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntegrasyon/MalzemeleriEntegreEt", ReplyAction="http://tempuri.org/IEntegrasyon/MalzemeleriEntegreEtResponse")]
        int MalzemeleriEntegreEt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntegrasyon/MalzemeBirimleriEntegreEt", ReplyAction="http://tempuri.org/IEntegrasyon/MalzemeBirimleriEntegreEtResponse")]
        int MalzemeBirimleriEntegreEt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntegrasyon/FirmalariEntegreEt", ReplyAction="http://tempuri.org/IEntegrasyon/FirmalariEntegreEtResponse")]
        int FirmalariEntegreEt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntegrasyon/PersonelleriEntegreEt", ReplyAction="http://tempuri.org/IEntegrasyon/PersonelleriEntegreEtResponse")]
        int PersonelleriEntegreEt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntegrasyon/PersonelBolumleriEntegreEt", ReplyAction="http://tempuri.org/IEntegrasyon/PersonelBolumleriEntegreEtResponse")]
        int PersonelBolumleriEntegreEt();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntegrasyonChannel : LKUI.EntegrasyonServisi.IEntegrasyon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntegrasyonClient : System.ServiceModel.ClientBase<LKUI.EntegrasyonServisi.IEntegrasyon>, LKUI.EntegrasyonServisi.IEntegrasyon {
        
        public EntegrasyonClient() {
        }
        
        public EntegrasyonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntegrasyonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntegrasyonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntegrasyonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int MalzemeleriEntegreEt() {
            return base.Channel.MalzemeleriEntegreEt();
        }
        
        public int MalzemeBirimleriEntegreEt() {
            return base.Channel.MalzemeBirimleriEntegreEt();
        }
        
        public int FirmalariEntegreEt() {
            return base.Channel.FirmalariEntegreEt();
        }
        
        public int PersonelleriEntegreEt() {
            return base.Channel.PersonelleriEntegreEt();
        }
        
        public int PersonelBolumleriEntegreEt() {
            return base.Channel.PersonelBolumleriEntegreEt();
        }
    }
}
